### PR TITLE
feat(): Added useConnection option

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, Added useConnection option, see here --> https://github.com/nestjs/nest/issues/5747

### CODE REVIEW

**Comment by Tony133** [comment]
Refers to this Issues: https://github.com/nestjs/nest/issues/5747

**Comment by jmcdo29** [comment]
It looks like the options to use a connection is added, but the logic behind using it isn't. Am I missing something?

**Comment by Tony133** [comment]
I was convinced that it was enough to add only the interface of the interface
Why do you know how I can complete it?

**Comment by jmcdo29** [comment]
@Tony133 make a test that uses `useConnection` to see if it is was enough. 

More than likely, you'll need to modify the logic of `typeorm-core.module.ts` to make the connection work

**Comment by Tony133** [comment]
ok thanks sorry

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/typeorm/issues/719#issuecomment-732745670

**Pull request closed without merging**
