### PR TITLE
Allow for feature modules to declare entities

### PR DESCRIPTION
**Pull request by SaaJoh0783**

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Haha wow. I even didn't realize that it's possible. Need to think about it but it sounds great! I'm just afraid that people would think that using `forFeature()` is necessary.

**Comment by SaaJoh0783** [comment]
Hmm... would you like it if I added a little bit of documentation?

**Comment by SaaJoh0783** [comment]
Just let me know what I can do to get this merged in.

**Comment by kamilmysliwiec** [comment]
Hi @SaaJoh0783,
The API has changed a little, and thus the PR is outdated now, but nevertheless thank you for your effort 🙂

**Pull request closed without merging**
